[tool.poetry]
name = "pldag"
version = "0.1.6"
description = ""
authors = ["znittzel <rikard@ourstudio.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
